### ISSUE TITLE
Standard/easier to find m2 screw lengths?

### ISSUE THREAD

**Issue by alairock** [atulloh/oddball#12]
This isn't really an issue with the design so much as it is a sourcing issue. The screw lengths are 18 and 22, which are both really tough to find. 

It would be really awesome if we could get those down to 16mm or shorter. I can find 16mm m2 screws much much easier. Otherwise I have to order them on alibaba and it takes weeks/months to arrive.

**Comment by alairock** [comment]
Modified the file for the shorter screws. Worked great! Excellent variable design!

**Comment by atulloh** [comment]
Hey @alairock , sorry, missed the notification for this. Glad you got it sorted out 😄 

If I ever get around to a redesign, I'll probably switch them for threaded inserts; much less fiddly!
