### ISSUE TITLE
Create build guide

### ISSUE THREAD

**Issue by atulloh** [atulloh/oddball#3]

**Comment by jdayton3** [comment]
@atulloh - if you have an extra set of PCBs you'd like to sell and would like someone to help with the build guide or be a beta tester or anything like that, feel free to hit me up! You can PM me at u/knot-a-robot, respond here, or find my other contact info at my GitHub profile -> home page if you're interested. I'm super excited about this project!

**Comment by atulloh** [comment]
Thanks @jdayton3 , I'll definitely need feedback on the build process; I'll keep you posted.

**Comment by keyboard-magpie** [comment]
hey @atulloh just ordered some v2 pcbs; does the build guide need an update to mention these? I saw the silks changed from teensy to elite c.

**Comment by atulloh** [comment]
Hey @keyboard-magpie ...

> hey @atulloh just ordered some v2 pcbs...

Wow, you're on ball! I've only just ordered some too, you might even beat me to it.

> ...does the build guide need an update to mention these? I saw the silks changed from teensy to elite c.

Yep. I never actually wrote a build guide for v1 (sorry @jdayton3 !). I'm just in the process of doing it for both v1/v2 on this work-in-progress branch: https://github.com/atulloh/oddball/tree/blog/v2. The formatting and images won't actually work correctly until it's merged into the GitHub pages branch as it's generated with Jekyll. I also probably won't merge it in until I've actually finished a build, which will be several weeks as I'm still waiting for parts to arrive.

The main changes for v2 were:
- switched to Elite C
- added support for PMW3360 (although you can still use an ADNS9800)

I'll update this issue when I get around to merging the build guide in.

**Comment by keyboard-magpie** [comment]
I should ask, are there any case differences between v1 and 2?

**Comment by atulloh** [comment]
Yep, slight changes, mainly to:
- make assembly easier
- make room for the PMW3360

You can see the work-in-progress files here: https://github.com/atulloh/oddball/blob/develop/v2.0/output/case/v2.0/

Hopefully I can get my printer back in the next week or two (we are under lockdown due to virus), then do some test prints, make some measurements, and get the case files finished up.

**Comment by keyboard-magpie** [comment]
Good timing! :D 

I'm printing v2 case files now.

V2 pcbs en route by DHL from JLCPCB.

Are you on discord anywhere?

**Comment by atulloh** [comment]
@keyboard-magpie nice! Like I said though, the cases are a work-in-progress; I'll need to tweak the cable cutouts. I'll probably also try to reduce the height a bit. I'll merge that `develop/v2.0` branch back into `master` when I've had a chance that every fits together okay.

Sure, discord is tullonator#6580

**Comment by gorbachev** [comment]
I just finished printing the cases...doing a test run with 3D printed plates before shelling out the money for plates with more expensive materials. Case design looks simple enough to figure out without a build guide. I'm familiar with Kicad, so the connections to the thumb PCBs / trackball controller looks pretty intuitive. The spacers / screw sizing will be a bit of experimentation I guess. Not quite there yet.

BTW, kudos on the case design. It prints really easily. Assembly is also really simple.

I could use a bit of help with the actual trackball, however. The only place I could find any information about it was your Reddit post on /r/mk. So you're using a mini pool ball and ceramic balls embedded into the mount.

What size is that mini pool ball? Last time I looked on eBay there were a few different sizes and I couldn't figure out which size is the right one. 1.5" seemed to be the most common size, but there are sizes ranging from 1" to 2".

Also where would I go and buy the small ceramic balls, and what size are they?

**Comment by atulloh** [comment]
Hey @gorbachev, to answer your questions:

> ...The spacers / screw sizing will be a bit of experimentation I guess

- 18mm M2 bolts x12 (most case fixings and trackball assembly)
- 22mm M2 bolts x2 (right thumb cluster)
- M2 nuts x12
- the spacer between the plate and sensor is just the `adnsCover.stl` or `pmwCover.stl` depending on which sensor you are using

Looking back, I wish I'd used threaded inserts for all the bolts :(

> ... So you're using a mini pool ball and ceramic balls embedded into the mount.

Yep.

> What size is that mini pool ball? 

0.98"/~25mm diameter, I used something like https://www.amazon.com/CAOREN-16pcs-Billiard-Children-Accessories/dp/B0836WQQF5

> Also where would I go and buy the small ceramic balls, and what size are they?

1/8"/3.175mm diameter, I used Si3N4 ones like https://www.amazon.com/uxcell-Ceramic-Bearing-Silicon-Precision/dp/B07ZKTYTFJ/ref=sr_1_2?dchild=1&keywords=si3n4+balls+1%2F8&qid=1609759332&sr=8-2

It's good to get a few extra of whatever you get, they are pretty easier to drop/lose.

Good luck. Although it's this keyboard's second iteration, it's the first keyboard I've really designed, and isn't as easy to put together as it could have been. If you have further questions, feel free to post here, or you can add me on Discord, my details are in my previous comment above.

As a general update for this issue: I've made a fair start and taken most of the photos needed, just waiting for a new PC power supply to arrive so I can get back to my dev environment and get it all wrapped up!

**Comment by gorbachev** [comment]
This is great! Thank you!

**Comment by atulloh** [comment]
> * M2 nuts x12

Sorry, I meant x14.

**Comment by atulloh** [comment]
This has been merged in. If anyone has any feedback or wants changes, I think you can open an issue in GitHub.

@gorbachev if you get around to making a build, I've added a section where people can add photos of their Oddball builds https://atulloh.github.io/oddball/community-builds.html

It's a tricky build, so I doubt there will be many, but prove me wrong 😛

**Comment by atulloh** [comment]
See previous comment.

**Comment by atulloh** [comment]
Oh, and for the record, the build guide is: https://atulloh.github.io/oddball/v2/build-guide.html
